export * from "./Border";
export * from "./Colors";
export * from "./FontSizes";
export * from "./Margin";
export * from "./Opacity";
export * from "./Padding";
export * from "./Text";
export * from "./Image";
export * from "./Button";
export * from "./Stack";
export * from "./TooltipComp";
export * from './Text'
